In [1]:
# ===============
# libraries
# ===============

import os, gc, yaml, glob, pickle
import time
import random
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm

import warnings
# warnings.filterwarnings('ignore')

# original
import sys
sys.path.append("../src")
from utils.data import sep, show_df, glob_walk, set_seed, save_config_yaml, dict_to_namespace

from datetime import datetime
date = datetime.now().strftime("%Y%m%d")
print(f"TODAY is {date}")

TODAY is 20260111

In [2]:
# =================
# Load data 
# =================
pp_df = pl.read_csv("/mnt/nfs/home/hidebu/study/CSIRO---Image2Biomass-Prediction/data/processed/010_preprocess_from_publicnotebook/csiro_data_split.csv")
my_pp_df = pl.read_csv("/mnt/nfs/home/hidebu/study/CSIRO---Image2Biomass-Prediction/data/processed/001_preprocess_ver04/df_pivot.csv")

sep("pp_df"); show_df(pp_df, 3, True); 
sep("my_pp_df"); show_df(my_pp_df, 3, True);

================================================================================
pp_df
================================================================================
(357, 1165)

shape: (3, 1_165)
┌─────────────┬─────────────┬───────┬─────────────┬───┬───────────┬───────────┬─────────────┬──────┐
│ image_path  ┆ Sampling_Da ┆ State ┆ Species     ┆ … ┆ emb1151   ┆ emb1152   ┆ Sampling_Da ┆ fold │
│ ---         ┆ te          ┆ ---   ┆ ---         ┆   ┆ ---       ┆ ---       ┆ te_Month    ┆ ---  │
│ str         ┆ ---         ┆ str   ┆ str         ┆   ┆ f64       ┆ f64       ┆ ---         ┆ i64  │
│             ┆ str         ┆       ┆             ┆   ┆           ┆           ┆ i64         ┆      │
╞═════════════╪═════════════╪═══════╪═════════════╪═══╪═══════════╪═══════════╪═════════════╪══════╡
│ /kaggle/inp ┆ 2015/9/4    ┆ Tas   ┆ Ryegrass_Cl ┆ … ┆ -0.500009 ┆ -0.611312 ┆ 9           ┆ 1    │
│ ut/csiro-bi ┆             ┆       ┆ over        ┆   ┆           ┆           ┆             ┆      │
│ omass/tr…   ┆             ┆       ┆             ┆   ┆           ┆           ┆             ┆      │
│ /kaggle/inp ┆ 2015/4/1    ┆ NSW   ┆ Lucerne     ┆ … ┆ 0.045089  ┆ -0.035254 ┆ 4           ┆ 4    │
│ ut/csiro-bi ┆             ┆       ┆             ┆   ┆           ┆           ┆             ┆      │
│ omass/tr…   ┆             ┆       ┆             ┆   ┆           ┆           ┆             ┆      │
│ /kaggle/inp ┆ 2015/9/1    ┆ WA    ┆ SubcloverDa ┆ … ┆ -0.103918 ┆ -0.623414 ┆ 9           ┆ 2    │
│ ut/csiro-bi ┆             ┆       ┆ lkeith      ┆   ┆           ┆           ┆             ┆      │
│ omass/tr…   ┆             ┆       ┆             ┆   ┆           ┆           ┆             ┆      │
└─────────────┴─────────────┴───────┴─────────────┴───┴───────────┴───────────┴─────────────┴──────┘

shape: (3, 1_165)
┌──────────────┬──────────────┬───────┬──────────┬───┬───────────┬───────────┬──────────────┬──────┐
│ image_path   ┆ Sampling_Dat ┆ State ┆ Species  ┆ … ┆ emb1151   ┆ emb1152   ┆ Sampling_Dat ┆ fold │
│ ---          ┆ e            ┆ ---   ┆ ---      ┆   ┆ ---       ┆ ---       ┆ e_Month      ┆ ---  │
│ str          ┆ ---          ┆ str   ┆ str      ┆   ┆ f64       ┆ f64       ┆ ---          ┆ i64  │
│              ┆ str          ┆       ┆          ┆   ┆           ┆           ┆ i64          ┆      │
╞══════════════╪══════════════╪═══════╪══════════╪═══╪═══════════╪═══════════╪══════════════╪══════╡
│ /kaggle/inpu ┆ 2015/2/24    ┆ NSW   ┆ Phalaris ┆ … ┆ -0.153629 ┆ -0.292729 ┆ 2            ┆ 0    │
│ t/csiro-biom ┆              ┆       ┆          ┆   ┆           ┆           ┆              ┆      │
│ ass/tr…      ┆              ┆       ┆          ┆   ┆           ┆           ┆              ┆      │
│ /kaggle/inpu ┆ 2015/7/8     ┆ WA    ┆ Clover   ┆ … ┆ -0.309601 ┆ -0.614334 ┆ 7            ┆ 4    │
│ t/csiro-biom ┆              ┆       ┆          ┆   ┆           ┆           ┆              ┆      │
│ ass/tr…      ┆              ┆       ┆          ┆   ┆           ┆           ┆              ┆      │
│ /kaggle/inpu ┆ 2015/9/1     ┆ WA    ┆ Ryegrass ┆ … ┆ -0.449513 ┆ -0.041214 ┆ 9            ┆ 2    │
│ t/csiro-biom ┆              ┆       ┆          ┆   ┆           ┆           ┆              ┆      │
│ ass/tr…      ┆              ┆       ┆          ┆   ┆           ┆           ┆              ┆      │
└──────────────┴──────────────┴───────┴──────────┴───┴───────────┴───────────┴──────────────┴──────┘

================================================================================
my_pp_df
================================================================================
(357, 36)

shape: (3, 36)
┌─────────────┬─────────────┬────────────┬───────┬───┬────────────┬────────────┬────────────┬──────┐
│ image_id    ┆ image_path  ┆ Sampling_D ┆ State ┆ … ┆ is_Subclov ┆ is_Subclov ┆ is_WhiteCl ┆ Fold │
│ ---         ┆ ---         ┆ ate        ┆ ---   ┆   ┆ erDalkeith ┆ erLosa     ┆ over       ┆ ---  │
│ str         ┆ str         ┆ ---        ┆ str   ┆   ┆ ---        ┆ ---        ┆ ---        ┆ i64  │
│             ┆             ┆ str        ┆       ┆   ┆ bool       ┆ bool       ┆ bool       ┆      │
╞═════════════╪═════════════╪════════════╪═══════╪═══╪════════════╪════════════╪════════════╪══════╡
│ ID101148565 ┆ train/ID101 ┆ 2015/9/4   ┆ Tas   ┆ … ┆ false      ┆ false      ┆ false      ┆ 2    │
│ 6           ┆ 1485656.jpg ┆            ┆       ┆   ┆            ┆            ┆            ┆      │
│ ID101226053 ┆ train/ID101 ┆ 2015/4/1   ┆ NSW   ┆ … ┆ false      ┆ false      ┆ false      ┆ 2    │
│ 0           ┆ 2260530.jpg ┆            ┆       ┆   ┆            ┆            ┆            ┆      │
│ ID102523438 ┆ train/ID102 ┆ 2015/9/1   ┆ WA    ┆ … ┆ true       ┆ false      ┆ false      ┆ 1    │
│ 8           ┆ 5234388.jpg ┆            ┆       ┆   ┆            ┆            ┆            ┆      │
└─────────────┴─────────────┴────────────┴───────┴───┴────────────┴────────────┴────────────┴──────┘

shape: (3, 36)
┌─────────────┬─────────────┬────────────┬───────┬───┬────────────┬────────────┬────────────┬──────┐
│ image_id    ┆ image_path  ┆ Sampling_D ┆ State ┆ … ┆ is_Subclov ┆ is_Subclov ┆ is_WhiteCl ┆ Fold │
│ ---         ┆ ---         ┆ ate        ┆ ---   ┆   ┆ erDalkeith ┆ erLosa     ┆ over       ┆ ---  │
│ str         ┆ str         ┆ ---        ┆ str   ┆   ┆ ---        ┆ ---        ┆ ---        ┆ i64  │
│             ┆             ┆ str        ┆       ┆   ┆ bool       ┆ bool       ┆ bool       ┆      │
╞═════════════╪═════════════╪════════════╪═══════╪═══╪════════════╪════════════╪════════════╪══════╡
│ ID980538882 ┆ train/ID980 ┆ 2015/2/24  ┆ NSW   ┆ … ┆ false      ┆ false      ┆ false      ┆ 0    │
│             ┆ 538882.jpg  ┆            ┆       ┆   ┆            ┆            ┆            ┆      │
│ ID980878870 ┆ train/ID980 ┆ 2015/7/8   ┆ WA    ┆ … ┆ false      ┆ false      ┆ false      ┆ 0    │
│             ┆ 878870.jpg  ┆            ┆       ┆   ┆            ┆            ┆            ┆      │
│ ID983582017 ┆ train/ID983 ┆ 2015/9/1   ┆ WA    ┆ … ┆ false      ┆ false      ┆ false      ┆ 1    │
│             ┆ 582017.jpg  ┆            ┆       ┆   ┆            ┆            ┆            ┆      │
└─────────────┴─────────────┴────────────┴───────┴───┴────────────┴────────────┴────────────┴──────┘

In [4]:
pp_df["image_path"].to_list()[:3]

['/kaggle/input/csiro-biomass/train/ID1011485656.jpg',
 '/kaggle/input/csiro-biomass/train/ID1012260530.jpg',
 '/kaggle/input/csiro-biomass/train/ID1025234388.jpg']

In [7]:
print(my_pp_df.columns)

['image_id', 'image_path', 'Sampling_Date', 'State', 'Species', 'Pre_GSHH_NDVI', 'Height_Ave_cm', 'Dry_Clover_g', 'Dry_Dead_g', 'Dry_Green_g', 'Dry_Total_g', 'GDM_g', 'date', 'year', 'month', 'day', 'weekday', 'year_month', 'weekday_name', 'is_BarleyGrass', 'is_Barleygrass', 'is_Bromegrass', 'is_Capeweed', 'is_Clover', 'is_CrumbWeed', 'is_Fescue', 'is_Lucerne', 'is_Mixed', 'is_Phalaris', 'is_Ryegrass', 'is_SilverGrass', 'is_SpearGrass', 'is_SubcloverDalkeith', 'is_SubcloverLosa', 'is_WhiteClover', 'Fold']

In [8]:
select_cols = ['image_id', 'image_path', 'Sampling_Date', 'State', 'Species', 'Pre_GSHH_NDVI', 'Height_Ave_cm', 'Dry_Clover_g', 'Dry_Dead_g', 'Dry_Green_g', 'Dry_Total_g', 'GDM_g', 'fold']

In [10]:
pp_df = (
    pp_df.with_columns([
        pl.col("image_path").map_elements(lambda x: os.path.basename(x).split(".")[0], return_dtype=pl.Utf8).alias("image_id"),
        pl.col("image_path").map_elements(lambda x: os.path.basename(x), return_dtype=pl.Utf8).alias("image_path"),
    ])
    .select(select_cols)
    .rename({"fold":"Fold"})
    )

pp_df

shape: (357, 13)
┌─────────────┬─────────────┬─────────────┬───────┬───┬─────────────┬─────────────┬─────────┬──────┐
│ image_id    ┆ image_path  ┆ Sampling_Da ┆ State ┆ … ┆ Dry_Green_g ┆ Dry_Total_g ┆ GDM_g   ┆ Fold │
│ ---         ┆ ---         ┆ te          ┆ ---   ┆   ┆ ---         ┆ ---         ┆ ---     ┆ ---  │
│ str         ┆ str         ┆ ---         ┆ str   ┆   ┆ f64         ┆ f64         ┆ f64     ┆ i64  │
│             ┆             ┆ str         ┆       ┆   ┆             ┆             ┆         ┆      │
╞═════════════╪═════════════╪═════════════╪═══════╪═══╪═════════════╪═════════════╪═════════╪══════╡
│ ID101148565 ┆ ID101148565 ┆ 2015/9/4    ┆ Tas   ┆ … ┆ 16.2751     ┆ 48.2735     ┆ 16.275  ┆ 1    │
│ 6           ┆ 6.jpg       ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
│ ID101226053 ┆ ID101226053 ┆ 2015/4/1    ┆ NSW   ┆ … ┆ 7.6         ┆ 7.6         ┆ 7.6     ┆ 4    │
│ 0           ┆ 0.jpg       ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
│ ID102523438 ┆ ID102523438 ┆ 2015/9/1    ┆ WA    ┆ … ┆ 0.0         ┆ 6.05        ┆ 6.05    ┆ 2    │
│ 8           ┆ 8.jpg       ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
│ ID102861117 ┆ ID102861117 ┆ 2015/5/18   ┆ Tas   ┆ … ┆ 24.2376     ┆ 55.2079     ┆ 24.2376 ┆ 1    │
│ 5           ┆ 5.jpg       ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
│ ID103594794 ┆ ID103594794 ┆ 2015/9/11   ┆ Tas   ┆ … ┆ 10.5261     ┆ 34.1844     ┆ 10.9605 ┆ 1    │
│ 9           ┆ 9.jpg       ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
│ …           ┆ …           ┆ …           ┆ …     ┆ … ┆ …           ┆ …           ┆ …       ┆ …    │
│ ID975115267 ┆ ID975115267 ┆ 2015/7/8    ┆ WA    ┆ … ┆ 0.8         ┆ 40.83       ┆ 40.83   ┆ 4    │
│             ┆ .jpg        ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
│ ID978026131 ┆ ID978026131 ┆ 2015/9/4    ┆ Tas   ┆ … ┆ 12.0601     ┆ 40.8994     ┆ 36.7046 ┆ 1    │
│             ┆ .jpg        ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
│ ID980538882 ┆ ID980538882 ┆ 2015/2/24   ┆ NSW   ┆ … ┆ 91.6543     ┆ 92.8        ┆ 91.6543 ┆ 0    │
│             ┆ .jpg        ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
│ ID980878870 ┆ ID980878870 ┆ 2015/7/8    ┆ WA    ┆ … ┆ 2.0325      ┆ 34.39       ┆ 34.39   ┆ 4    │
│             ┆ .jpg        ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
│ ID983582017 ┆ ID983582017 ┆ 2015/9/1    ┆ WA    ┆ … ┆ 40.94       ┆ 40.94       ┆ 40.94   ┆ 2    │
│             ┆ .jpg        ┆             ┆       ┆   ┆             ┆             ┆         ┆      │
└─────────────┴─────────────┴─────────────┴───────┴───┴─────────────┴─────────────┴─────────┴──────┘

In [ ]:
pp_df.write_csv("/mnt/nfs/home/hidebu/study/CSIRO---Image2Biomass-Prediction/data/processed/010_preprocess_from_publicnotebook/df_pivot.csv")